
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label lblAnchorNote;
	
	private global::Gtk.ComboBox cmbAnchorNote;
	
	private global::Gtk.ComboBox cmbAnchorOctave;
	
	private global::Gtk.Entry entAnchorFrequency;
	
	private global::Gtk.Label lblAnchorFrequency;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label lblFrequency;
	
	private global::Gtk.Entry entFrequency;
	
	private global::Gtk.HScale hscFrequency;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Label lblNote;
	
	private global::Gtk.ComboBox cmbNote;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Label lblOctave;
	
	private global::Gtk.ComboBox cmbOctave;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Label lblOffset;
	
	private global::Gtk.Entry entOffset;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Equal Tempered Note<->Frequency Converter");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(20));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox = new global::Gtk.VBox ();
		this.vbox.Name = "vbox";
		this.vbox.Spacing = 6;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblAnchorNote = new global::Gtk.Label ();
		this.lblAnchorNote.Name = "lblAnchorNote";
		this.lblAnchorNote.LabelProp = global::Mono.Unix.Catalog.GetString ("        Anchor Note");
		this.hbox3.Add (this.lblAnchorNote);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblAnchorNote]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cmbAnchorNote = global::Gtk.ComboBox.NewText ();
		this.cmbAnchorNote.Name = "cmbAnchorNote";
		this.hbox3.Add (this.cmbAnchorNote);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmbAnchorNote]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.cmbAnchorOctave = global::Gtk.ComboBox.NewText ();
		this.cmbAnchorOctave.Name = "cmbAnchorOctave";
		this.hbox3.Add (this.cmbAnchorOctave);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.cmbAnchorOctave]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entAnchorFrequency = new global::Gtk.Entry ();
		this.entAnchorFrequency.CanFocus = true;
		this.entAnchorFrequency.Name = "entAnchorFrequency";
		this.entAnchorFrequency.IsEditable = true;
		this.entAnchorFrequency.InvisibleChar = '●';
		this.hbox3.Add (this.entAnchorFrequency);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entAnchorFrequency]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 3;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblAnchorFrequency = new global::Gtk.Label ();
		this.lblAnchorFrequency.Name = "lblAnchorFrequency";
		this.lblAnchorFrequency.LabelProp = global::Mono.Unix.Catalog.GetString ("                  Anchor Frequency (Hz)");
		this.hbox3.Add (this.lblAnchorFrequency);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblAnchorFrequency]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblFrequency = new global::Gtk.Label ();
		this.lblFrequency.Name = "lblFrequency";
		this.lblFrequency.Xpad = 38;
		this.lblFrequency.LabelProp = global::Mono.Unix.Catalog.GetString ("Frequency (Hz)");
		this.hbox2.Add (this.lblFrequency);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblFrequency]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entFrequency = new global::Gtk.Entry ();
		this.entFrequency.CanDefault = true;
		this.entFrequency.CanFocus = true;
		this.entFrequency.Name = "entFrequency";
		this.entFrequency.IsEditable = true;
		this.entFrequency.InvisibleChar = '●';
		this.entFrequency.Xalign = 0.01F;
		this.hbox2.Add (this.entFrequency);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entFrequency]));
		w8.Position = 1;
		this.vbox7.Add (this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox2]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hscFrequency = new global::Gtk.HScale (null);
		this.hscFrequency.CanFocus = true;
		this.hscFrequency.Name = "hscFrequency";
		this.hscFrequency.Adjustment.Lower = 16;
		this.hscFrequency.Adjustment.Upper = 8000;
		this.hscFrequency.Adjustment.PageIncrement = 10;
		this.hscFrequency.Adjustment.StepIncrement = 1;
		this.hscFrequency.DrawValue = false;
		this.hscFrequency.Digits = 4;
		this.hscFrequency.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox7.Add (this.hscFrequency);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hscFrequency]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox.Add (this.vbox7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox [this.vbox7]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.lblNote = new global::Gtk.Label ();
		this.lblNote.Name = "lblNote";
		this.lblNote.LabelProp = global::Mono.Unix.Catalog.GetString ("Note");
		this.vbox4.Add (this.lblNote);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblNote]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.cmbNote = global::Gtk.ComboBox.NewText ();
		this.cmbNote.Name = "cmbNote";
		this.vbox4.Add (this.cmbNote);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.cmbNote]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.lblOctave = new global::Gtk.Label ();
		this.lblOctave.Name = "lblOctave";
		this.lblOctave.LabelProp = global::Mono.Unix.Catalog.GetString ("Octave");
		this.vbox5.Add (this.lblOctave);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.lblOctave]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.cmbOctave = global::Gtk.ComboBox.NewText ();
		this.cmbOctave.Name = "cmbOctave";
		this.vbox5.Add (this.cmbOctave);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.cmbOctave]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox1.Add (this.vbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.lblOffset = new global::Gtk.Label ();
		this.lblOffset.Name = "lblOffset";
		this.lblOffset.LabelProp = global::Mono.Unix.Catalog.GetString ("Offset (Hz)");
		this.vbox6.Add (this.lblOffset);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.lblOffset]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.entOffset = new global::Gtk.Entry ();
		this.entOffset.CanDefault = true;
		this.entOffset.CanFocus = true;
		this.entOffset.Name = "entOffset";
		this.entOffset.IsEditable = false;
		this.entOffset.InvisibleChar = '●';
		this.vbox6.Add (this.entOffset);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.entOffset]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox1.Add (this.vbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox6]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.vbox.Add (this.hbox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox [this.hbox1]));
		w21.Position = 2;
		this.Add (this.vbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.entFrequency.HasDefault = true;
		this.entOffset.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
